apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    labels:
      app: resourcemonitor
      version: master
    name: resourcemonitor
    namespace: kube-system
  spec:
    replicas: 1
    revisionHistoryLimit: 1
    selector:
      matchLabels:
        app: resourcemonitor
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        annotations:
          prometheus.io/port: "7000"
          prometheus.io/scrape: "true"
        labels:
          app: resourcemonitor
          version: master
      spec:
        automountServiceAccountToken: true
        containers:
        - image: CHANGEME:latest
          imagePullPolicy: Always
          name: resourcemonitor
          ports:
          - containerPort: 7000
            name: metrics
            protocol: TCP
          env:
          - name: ETCD
            value: "comma,separated,list,of,your,etcd,servers,ip,addresses"
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: resourcemonitor
        serviceAccountName: resourcemonitor
        terminationGracePeriodSeconds: 30
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
