---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: resourcemonitor
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
   name: resource-monitor-role
rules:
 - apiGroups: ["*"]
   resources: ["nodes", "endpoints", "componentstatuses"]
   verbs: ["get", "list", "watch",]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resource-monitor-rolebinding
  namespace: 'kube-system'
subjects:
- kind: ServiceAccount
  name: resourcemonitor
  namespace: 'kube-system'
roleRef:
  kind: ClusterRole
  name: resource-monitor-role
  apiGroup: rbac.authorization.k8s.io